-- MySQL Script generated by MySQL Workbench
-- jeu. 25 mai 2023 14:21:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `profil` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gabarit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gabarit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ref_gabarit` INT NULL,
  `hauteur` DOUBLE NULL,
  `largeur` DOUBLE NULL,
  `point_prise_x` VARCHAR(45) NULL,
  `point_prise_y` VARCHAR(45) NULL,
  `point_prise_z` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recette` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ref_recette` VARCHAR(45) NULL,
  `nb_gabarit` INT NULL,
  `date_recette` DATETIME NULL,
  `user_id` INT NULL,
  `gabarit_id` INT NULL,
  `user_id1` INT NULL,
  `gabarit_id1` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recette_user_idx` (`user_id1` ASC) VISIBLE,
  INDEX `fk_recette_gabarit1_idx` (`gabarit_id1` ASC) VISIBLE,
  CONSTRAINT `fk_recette_user`
    FOREIGN KEY (`user_id1`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recette_gabarit1`
    FOREIGN KEY (`gabarit_id1`)
    REFERENCES `mydb`.`gabarit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alarme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alarme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_alarme` DATETIME NULL,
  `code_erreur` VARCHAR(45) NULL,
  `user_id1` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_alarme_user1_idx` (`user_id1` ASC) VISIBLE,
  CONSTRAINT `fk_alarme_user1`
    FOREIGN KEY (`user_id1`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
